# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-18 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name_two',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name 2'),
        ),
    ]
