"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import django_heroku

from webapp.settings import *


STATIC_ROOT = os.path.join(BASE_DIR, 'static_produccion')


# Extra config
CSRF_TRUSTED_ORIGINS = [
    '.localhost.pe',
    'boiling-temple-49703.herokuapp.com'
]

django_heroku.settings(locals())